{% set version = "1.14.3" %}

package:
  name: elixir
  version: {{ version }}

source:
  url: https://github.com/elixir-lang/elixir/archive/v{{ version }}.tar.gz
  sha256: bd464145257f36bd64f7ba8bed93b6499c50571b415c491b20267d27d7035707

build:
  number: 1
  skip: true  # [win]
  script: make prefix=${PREFIX} install

requirements:
  build:
    - make
  host:
    - git
  host:
    - erlang >=21.0
  run:
    - erlang >=21.0

test:
  commands:
    - elixir --version
    # this apparently hangs, now
    # - iex --version
    - mix --version

about:
  home: https://elixir-lang.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Elixir is a dynamic, functional language designed for building scalable and maintainable applications
  dev_url: https://github.com/elixir-lang/elixir
  doc_url: https://elixir-lang.org/docs.html
  doc_source_url: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/docs.exs

extra:
  recipe-maintainers:
    - bollwyvl
